name: Deploy Frontend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/karta_connect_frontend

            git pull origin main

            npm install

            npm run build

            sudo rm -rf /var/www/html/*

            sudo cp -r dist/* /var/www/html/

            sudo systemctl restart nginx
